# Generated by Django 5.1.4 on 2025-01-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_24_hour', models.BooleanField(default=False)),
                ('show_time', models.BooleanField(default=True)),
                ('show_date', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='refresh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screen',
            name='clock',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='background.clock'),
        ),
    ]
