# Generated by Django 5.1.4 on 2025-01-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0002_clock_screen_refresh_screen_clock'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='x',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='clock',
            name='y',
            field=models.IntegerField(default=50),
        ),
    ]
