# Generated by Django 5.1.4 on 2025-01-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0003_clock_x_clock_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clock',
            name='use_24_hour',
        ),
        migrations.AddField(
            model_name='clock',
            name='date_format',
            field=models.CharField(default='%-d/%-m/%Y', max_length=64),
        ),
        migrations.AddField(
            model_name='clock',
            name='size',
            field=models.CharField(default='5rem', max_length=16),
        ),
        migrations.AddField(
            model_name='clock',
            name='time_format',
            field=models.CharField(default='%-I:%M:%S %p', max_length=64),
        ),
    ]
